config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/add_email' => 'omniauth_callbacks#add_email'
  end

  get 'search', to: 'search#search', as: :search

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_reset
    end
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :questions, concerns: :votable do
    resources :comments, defaults: { commentable: 'questions' }
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, defaults: { commentable: 'answers' }
      patch :set_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root to: "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base

  include Votable
  include Commentable

  belongs_to :user
  has_many   :answers, dependent: :destroy
  has_many   :attachments, as: :attachable, dependent: :destroy
  has_many   :subscriptions, dependent: :destroy

  scope :last_day_questions, -> { where(created_at: 1.day.ago.all_day) }

  validates  :user_id, :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  scope :created_yesterday, -> { where(created_at: Time.zone.yesterday.all_day) }
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: QuestionSerializer::Question
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    respond_with @question
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :load_subscription, only: [:show]
  after_action :publish_question, only: :create

  include Voted

  respond_to :js, :json

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    gon.user_id = current_user.id if current_user
    gon.question_user_id = @question.user_id
    respond_with(@answer = @question.answers.build)
  end

  def new
    respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    current_user.author_of?(@question) ? respond_with(@question.destroy) : respond_with(@question)
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def load_subscription
    @subscription = @question.subscriptions.find_by(user: current_user) || Subscription.new
  end

  def publish_question
    PrivatePub.publish_to "/questions", question: render_to_string('questions/show.json.jbuilder') if @question.valid?
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
.panel.panel-default
  .panel-heading
    - @question.answers.each do |answer|
      -if answer.persisted?
        - cache answer do
          .panel-footer
            p= answer.body
            ul
              - answer.attachments.each do |a|
                li= link_to a.file.identifier, a.file.url
        -if answer.best == true
          p
            span.badge = "Best answer"
        - if can?(:set_best, answer) && answer.best == false
          p= link_to 'Set as the best', set_best_answer_path(question_id: @question.id, id: answer.id), method: :patch, remote: true
        - if can?(:manage, answer)
          p= link_to 'Edit', '', data: { answer_id: answer.id }, class: 'edit-answer-link'
          p= form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
              p= f.label :body, "Answer"
              p= f.text_area :body
              = f.fields_for :attachments do |a|
                = render 'attachments/attachment_fields', f: a
              .links
                = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
              p= f.submit 'Save'
          p= link_to 'Delete answer', [answer], remote: true, method: :delete, data: {confirm: 'Are you sure?'}
        .answer-votes id="#{dom_id(answer)}"
          = render 'votes/votes', object: answer
        .comments-list id="#{dom_id(answer)}"
          = render answer.comments
        - if can?(:create, Comment)
          = render 'comments/form', commentable: answer

app/views/questions/_question.html.slim
.panel.panel-default
  .panel-heading
    h3= @question.title
  .panel-body
    p= @question.body
    p Attachments:
    ul
      - @question.attachments.each do |a|
        li= link_to a.file.identifier, a.file.url
    = render 'subscriptions/subscription', question: @question
  .panel-footer
    =link_to 'To the questions list', questions_path
    - if can?(:manage, @question)
      p
      p= link_to 'Edit question', '', class: 'edit-question-link'
      p= link_to 'Delete question', @question, method: :delete, data: {confirm: "Are you sure?"}
      .edit-question
        = form_for [@question], remote: true do |f|
          .question-errors
          p
            = f.label :title
            = f.text_field :title
          p
            = f.label :body
            = f.text_area :body
            = f.fields_for :attachments do |a|
              = render 'attachments/attachment_fields', f: a
            .links
              = link_to_add_association 'Add file',
                                        f,
                                        :attachments,
                                        { :'data-association-insertion-method' => :before,
                                          partial: 'attachments/attachment_fields' }
          p= f.submit
          = link_to 'Cancel', question_path(@question), class: 'btn btn-default'

app/views/questions/index.html.slim
-if can?(:create, Question)
    p= link_to 'Log out', destroy_user_session_path, method: :delete
    p= link_to 'Ask question', new_question_path
- else
    p= link_to 'Log in', new_user_session_path
    p= link_to 'Sign up', new_user_registration_path
.search
  = render 'search/form'
h3
  | Questions list
.question-list
- cache collection_cache_key_for :question do
  - @questions.each do |question|
    .row.question id="#{dom_id(question)}"
      .panel.panel-default
      .panel-heading
        = link_to question.title, question_path(question)

= subscribe_to "/questions"

app/views/questions/new.html.slim
= form_for @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
    = f.fields_for :attachments do |a|
      = render 'attachments/attachment_fields', f: a
    .links
      = link_to_add_association 'Add file', f, :attachments, partial: 'attachments/attachment_fields'
  p= f.submit 'Create'

app/views/questions/show.html.slim
-cache @question do
  h1
    | Question:
  .question data-question-id = @question.id
    = render 'question'
  .question-votes
    = render 'votes/votes', object: @question
  .question-comments
    .comments-list id="#{dom_id(@question)}"
    = render @question.comments
    = render 'comments/form', commentable: @question

  h2
    | Answers:
  .answers
    = render 'answers'

  answer-form
    = render 'answers/form'

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"
= subscribe_to "/questions/#{@question.id}/answers/comments"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
      $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.question').html('<%= j render @question %>');
<% end %>