config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/add_email' => 'omniauth_callbacks#add_email'
  end

  get 'search', to: 'search#search', as: :search

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_reset
    end
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :questions, concerns: :votable do
    resources :comments, defaults: { commentable: 'questions' }
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, defaults: { commentable: 'answers' }
      patch :set_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root to: "questions#index"

end

app/models/search.rb
class Search
  RESOURCES = %w(User Question Answer Comment)

  def self.search(query, resource, options = {})
    return unless query.present?
    escaped_query = Riddle::Query.escape(query)
    klass = resource.constantize if resource.in?(RESOURCES)

    ThinkingSphinx.search escaped_query, { classes: [klass] }.merge(options)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check

  def search
    @resources = Search.search params[:query], params[:resource], page: params[:page], per_page: 15
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def index_type
    %w(Questions Answers Comments Users Everywhere)
  end
end

app/views/search/_form.html.slim
.search-resources
  .row
    .col-lg-9
      h4 Search
      = form_tag search_path, method: :get do
        .row
          .col-xs-9
            = search_field_tag :query, params[:query], placeholder: 'Search...', class: 'form-control'
          .col-xs-2
            = select_tag :resource, options_for_select(Search::RESOURCES, params[:resource]), prompt: 'Anything', class: 'form-control'
          .col-xs-1
            = submit_tag 'Search', class: 'btn btn-primary'

app/views/search/search.html.slim
=link_to 'To the questions list', questions_path
= render 'search/form'
.row
  .col-xs-12
    .result
      - if @resources
        - @resources.each do |resource|
          - if resource.is_a?(Question)
            .question-summary
              .summary
                = link_to resource.title, resource
              .search-body
                = resource.body
          - elsif resource.is_a?(Answer)
            .question-summary
              .summary
                = link_to resource.question.title, resource.question
              .search-body
                = resource.body
          - elsif resource.is_a?(Comment)
            p = resource.body
          - elsif resource.is_a?(User)
            p = link_to resource.email, resource