config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/add_email' => 'omniauth_callbacks#add_email'
  end

  get 'search', to: 'search#search', as: :search

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_reset
    end
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :questions, concerns: :votable do
    resources :comments, defaults: { commentable: 'questions' }
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, defaults: { commentable: 'answers' }
      patch :set_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root to: "questions#index"

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :user_id, :question_id, presence: true
  validates :user_id, uniqueness: { scope: [:user_id, :question_id] }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:create, :destroy]
  before_action :set_subscription, only: :destroy

  respond_to :js
  authorize_resource

  def create
    respond_with @subscription = @question.subscriptions.create(user: current_user)
  end

  def destroy
    respond_with @subscription.destroy
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/views/subscriptions/_subscription.html.slim
.subscription
  - if can?(:create, Subscription.new(question: question, user: current_user))
    - if Subscription.exists?(user: current_user, question: question)
      = link_to 'Unsubscribe', question_subscription_path(question, @subscription), remote: true, method: :delete, class: 'btn-flat'
    - else
      = link_to 'Subscribe', question_subscriptions_path(question), remote: true, method: :post, class: 'btn-flat'

app/views/subscriptions/create.js.erb
$(".subscription").html("<%= j render 'subscription', question: @question %>");

app/views/subscriptions/destroy.js.erb
$(".subscription").html("<%= j render 'subscription', question: @question %>");