config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post '/add_email' => 'omniauth_callbacks#add_email'
  end

  get 'search', to: 'search#search', as: :search

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_reset
    end
  end

  resources :users, only: [:index, :show, :edit, :update]

  resources :questions, concerns: :votable do
    resources :comments, defaults: { commentable: 'questions' }
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: :votable, shallow: true do
      resources :comments, defaults: { commentable: 'answers' }
      patch :set_best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  root to: "questions#index"

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :value, presence: true
  validates :votable_id, presence: true
  validates :user_id, presence: true, uniqueness: { scope: [:votable_type, :votable_id] }

  def set_vote(value)
    self.value = value
    save
  end

  def reset_vote
    self.destroy
  end

  def self.rating
    sum(:value)
  end
end

app/views/votes/_votes.html.slim
.panel.panel-default
  .panel-footer
    .row
      - cache [object, :vote]
        | Rating: #{object.votes.rating}
  .row
    - if can? :vote, object
      .col-md-1
        | Votes:
      - if object.user_voted?(current_user)
        .col-md-1
          - if object.kind_of? Question
            = link_to 'Reset', vote_reset_question_path(object), method: :patch, remote: true, data: {type: :json}
          - if object.kind_of? Answer
            = link_to 'Reset', vote_reset_answer_path(id: object, question_id: object.question_id), method: :patch, remote: true, data: {type: :json}
      - else
        .col-md-1
          - if object.kind_of? Question
            = link_to 'Up', vote_up_question_path(object), method: :patch, remote: true, data: {type: :json}
          - if object.kind_of? Answer
            = link_to 'Up', vote_up_answer_path(id: object, question_id: object.question_id), method: :patch, remote: true, data: {type: :json}
        .col-md-1
          - if object.kind_of? Question
            = link_to 'Down', vote_down_question_path(object), method: :patch, remote: true, data: {type: :json}
          - if object.kind_of? Answer
            = link_to 'Down', vote_down_answer_path(id: object, question_id: object.question_id), method: :patch, remote: true, data: {type: :json}